### ISSUE TITLE
!xkcd crashes and burns

### ISSUE THREAD

**Issue by bdevorem** [JohnathonNow/wolfratbot#12]
`Unhandled exception in thread started by <bound method IRCbot.listen of <ircbot.IRCbot object at 0x11063df10>>
Traceback (most recent call last):
  File "/Users/bdevorem/endor/wolfratbot/src/ircbot.py", line 32, in listen
    self.on_chat(who, message)
  File "/Users/bdevorem/endor/wolfratbot/src/ircbot.py", line 18, in on_chat
    wrbcommands.handle(str(who), msg, self)
  File "/Users/bdevorem/endor/wolfratbot/src/wrbcommands.py", line 113, in handle
    COMMANDS[command](SENDER,TEXT,command,send)
  File "modules/web_scraper/comics.py", line 33, in xkcd
    r = requests.get(BASE)
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bdevorem/endor/wolfratbot/venv/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='xkcd.com', port=443): Max retries exceeded with url: /965/ (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

**Comment by bdevorem** [comment]
To be specific, crashes and burns on Mac OS El Capitan.
